# Generated by Django 5.2.7 on 2025-12-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('gonderen_ad', models.CharField(max_length=100)),
                ('gonderen_tel', models.CharField(max_length=20)),
                ('gonderen_adres', models.TextField()),
                ('alici', models.CharField(max_length=100)),
                ('alici_tel', models.CharField(max_length=20)),
                ('adres', models.TextField()),
                ('gonderi_turu', models.CharField(max_length=50)),
                ('agirlik', models.FloatField()),
                ('odeme_turu', models.CharField(max_length=50)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('fiyat', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('durum', models.CharField(choices=[('YOLDA', 'Yolda / İşleniyor'), ('DAGITIMDA', 'Dağıtımda'), ('TESLIM', 'Teslim Edildi')], default='YOLDA', max_length=20)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='CargoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.CharField(max_length=255)),
                ('detay', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis', to='cargoposts.cargo')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
