# Generated by Django 5.2.7 on 2025-12-24 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('arac_tipi', models.CharField(choices=[('Motor', 'Motosiklet'), ('Araba', 'Hafif Ticari'), ('Yaya', 'Yaya Kurye')], default='Motor', max_length=50, verbose_name='Araç Tipi')),
                ('müsait_mi', models.BooleanField(default=True, verbose_name='Çalışmaya Hazır mı?')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kurye',
                'verbose_name_plural': 'Kuryeler',
            },
        ),
    ]
