# Generated by Django 5.2.7 on 2025-12-24 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(choices=[('GECIKME', 'Teslimat Gecikmesi'), ('HASAR', 'Hasarlı Gönderi'), ('FIYAT', 'Fiyatlandırma Sorunu'), ('DIGER', 'Diğer')], default='DIGER', max_length=10, verbose_name='Talep Konusu')),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('BEKLEMEDE', 'Beklemede'), ('KAPALI', 'Kapalı')], default='ACIK', max_length=10, verbose_name='Ticket Durumu')),
                ('isim', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('mesaj', models.TextField(verbose_name='Talep İçeriği')),
                ('olusturma', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Destek Talebi (Ticket)',
                'verbose_name_plural': 'Destek Talepleri (Ticket)',
                'ordering': ['-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Yönetici Mesajı')),
                ('icerik', models.TextField(verbose_name='Mesaj İçeriği')),
                ('olusturma', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gönderim Tarihi')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Mesajı',
                'verbose_name_plural': 'Ticket Mesajları',
                'ordering': ['olusturma'],
            },
        ),
    ]
